# Generated by Django 5.2.6 on 2025-09-25 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('current_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trains_at_station', to='traffic_control.station')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains_heading_to', to='traffic_control.station')),
            ],
        ),
    ]
